---
- name: Webhook rulebook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        port: 5000
  rules:
    - name: Run playbook on message
      condition: event.payload.message is defined
      action:
        run_playbook:
          name: log-message.yml
